---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['aws_access_key_id'] %>
  aws_secret_access_key: <%= ENV['aws_secret_access_key'] %>
  aws_ssh_key_id: <%= ENV['aws_ssh_key_id'] || 'circleci' %>
  region:  <%= ENV['aws_ssh_key_id'] || 'us-west-1' %>
  availability_zone:  <%= ENV['aws_ssh_key_id'] || 'us-west-1c' %>
  username: ubuntu

provisioner:
  name: chef_solo
  environments_path: 'files/default/test/environments'

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: 'ami-fd2c2cb8'
    driver_config:
      require_chef_omnibus: latest

suites:
  - name: default
    provisioner:
      solo_rb:
        environment: integration
    run_list:
      - recipe[runnable_web::default]
      - recipe[minitest-handler]
    attributes:
