source 'https://api.berkshelf.com'

metadata

cookbook 'runnable_nodejs', git: 'git@github.com:CodeNow/runnable_nodejs-cookbook.git'

cookbook 'apt', github: 'opscode-cookbooks/apt'
cookbook 'build-essential', github: 'opscode-cookbooks/build-essential', tag: 'v2.0.4'

group :integration do
  cookbook 'chef-solo-search', github: 'edelight/chef-solo-search'
  cookbook 'minitest-handler', github: 'btm/minitest-handler-cookbook'
end
